version: '3.3'

services:
  personal-website:
    image: elaynelemos/vue:node-14.15
    container_name: personal_website_app
    working_dir: /home/app/
    volumes:
      - ./:/home/app/
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    entrypoint:
      - bash
