name: Publish Website

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version short description
        default: v1.0.0
        required: true

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build pages
        run: yarn run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist

      - name: Create version tag
        run: git tag ${{ github.event.inputs.version }}
